---
:authentication:
  :method: OAuth2
  :oauth2_client_id: 178517224030-mqs6ap9d5aup4uanh07boli2aes1nfmk.apps.googleusercontent.com
  :oauth2_client_secret: HUkGO79L64ZrDNMJ4F-OnPtB
  :developer_token: ePLafod1j5naoIH12Iz0sw
  :client_customer_id: 3937774822
  :user_agent: Ruby Falcon
  :oauth2_token:
    :access_token: ya29.GlsZBtRovKKq_gPb97c2csO-s7gx9JTLsmqw4U_6wM38kqZixn8eRY1v8YlsMOsVVmKRk8uV6JKampSiKdivkDKIRL8M9uwfdCZtwwMZH7OFbDYsrx_vwLPO7wPJ
    :refresh_token: 1/0-ycnOTEVW8ffuXSKU9SA8gdZu7HXlDw2tizrRetB3c
    :issued_at: 2018-09-15 07:42:30.851193000 -07:00
    :expires_in: 3600
    :id_token: 
:connection:
  :enable_gzip: false
:library:
  :log_level: INFO
